export const carInfo = [
  {
    id: 0,
    name: "BMWE36",
    Location: "Rzeszów, Millenium Hall",
    Availability: 17,
    Combustion: 18,
    Category: "Basic",
  },
  {
    id: 1,
    name: "Peugeot",
    Location: "Rzeszów, Galeria Rzeszów",
    Availability: 2,
    Combustion: 8,
    Category: "Standard",
  },
  {
    id: 2,
    name: "Mazda",
    Location: "Jasionka, Lotnisko",
    Availability: 7,
    Combustion: 9,
    Category: "Medium",
  },
  {
    id: 3,
    name: "Nissan",
    Location: "Jarosław, Stara Ujeżdżalnia",
    Availability: 4,
    Combustion: 13,
    Category: "Medium",
  },
  {
    id: 4,
    name: "Mustang",
    Location: "Krasne, Auchan ",
    Availability: 3,
    Combustion: 15,
    Category: "Premium",
  },
  {
    id: 5,
    name: "Audi",
    Location: "Rzeszów, Millenium Hall ",
    Availability: 1,
    Combustion: 12,
    Category: "Premium",
  },
];
